### ISSUE TITLE
README

### ISSUE THREAD

**Issue by gonzalonunez** [mayqiyue/OCSkeleton#3]
Hey! Awesome work making an Objective-C version of the library. Do you think maybe you can change the README a bit to differentiate it from mine? Just seems a bit weird to me that they're virtually identical 😅

**Comment by mayqiyue** [comment]
Hey! Sorry for the trouble. I had updated the README. ☺

**Comment by gonzalonunez** [comment]
Thanks! No problem at all, great work porting it over to Objective-C. I appreciate it 🙂
