### ISSUE TITLE
Xcode warning for unused funciton

### ISSUE THREAD

**Issue by adrian-niculescu** [mayqiyue/OCSkeleton#4]
For OCSkeleton version 0.5.0 distributed via CocoaPods
Xcode warns that the `transitionMaker` function defined in `OCSkeletonDefines.h` is unsed:
![warning](https://user-images.githubusercontent.com/15037449/83570668-228e0480-a52f-11ea-9571-a7652c75ce23.png)

**Comment by mayqiyue** [comment]
Please upgrade to version 0.5.1 :)
